import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CartDrawer from "@/components/cart/CartDrawer";
import WhatsAppFloatingButton from "@/components/common/WhatsAppFloatingButton";
import SearchModal from "@/components/layout/SearchModal";
import MobileTabBar from "@/components/layout/MobileTabBar";
import GlobalSizeGuideModal from "@/components/common/GlobalSizeGuideModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <CartDrawer />
        <SearchModal />
        <GlobalSizeGuideModal />
        <WhatsAppFloatingButton />
        <MobileTabBar />
      </body>
    </html>
  );
}
